### ISSUE TITLE
gitHub action を windows powershell で実行したい

### ISSUE THREAD

**Issue by seigot** [seigot/tetris#38]
gitHub action を windows powershell で実行したい

以下の辺り参照する。

GitHub ActionsでMSBuildによるビルドを行う
https://zenn.dev/shimat/articles/d9ed0345c9866e

GitHub Actions v2使ってMSBuildを試してみた
https://qiita.com/y428_b/items/f8e0c598238d75f808b1

**Comment by seigot** [comment]
こんな感じ？？

```
name: MSBuild
on: push
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      run: msbuild msbuild_actions_sample.sln
      shell: cmd
```
